### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by ukmoose** [nidayand/noreowfs#1]
Without a readme what does your node do that the node that follows the requested naming convention node-red-contrib-owfs node doesn't do?

**Comment by nidayand** [comment]
Sorry.. you were to quick :-) It is on its way. It is currently just a very simple node where you'll specify the path to retrieve a value from the owserver. I wrote it because node-red-contrib-owfs does not support hubs.

**Comment by njh** [comment]
Hi,

I am not sure what you mean when you say `node-red-contrib-owfs` does not support hubs?

Could you open an issue with details of what is broken please?
Keen to make sure all device types work properly.

Thanks!

nick.

**Comment by nidayand** [comment]
Hi,
I don't think it is broken but simply not designed for it. I tried your module first of course and it didn't detect devices that were in a sub-star. I have multiple trees of star schemas in my 1-wire setup. One for each building or floor. E.g.
- /uncached/1D.289E0F000000/counters.A : gives me the counter from the master tree
- /uncached/1F.286408000000/main/10.E20765020800/temperature : gives me the temp from a sub-star

1F.2864xxxxx is a DS2409 based hub. Similar to this one http://owfs.org/index.php?page=ds2409-microhub

If you get that kind of support I will simply refer to your node instead :-)

I hope this helps

Kind regards
peter

**Comment by njh** [comment]
Yes, that should work. I have just pushed a fix that should make long node paths like that appear in the path list correctly: njh/node-red-contrib-owfs#4

But in the currently released version you have to pass in the OWFS path via msg.topic:

``` javascript
msg.topic = "uncached/1F.286408000000/main/10.E20765020800/temperature";
```

I should probably get a DS2409 hub to test with. Or at least work out how to simulate one.

nick.

**Comment by nidayand** [comment]
Ok, thanks for the update. Let me know if you need some sample data
